#!/usr/bin/env python3
import os
import argparse

'''
The script must be run from the project root directory.
Usage: ./script --èr <experiment_name>
'''
def log_to_bk(experiment_name):

    # relative path
    exp_dir = os.path.join('my-experiments', experiment_name)
    log_path = os.path.join(exp_dir, 'trace.log')
    bk_path = os.path.join(exp_dir, 'bk.pl')
    exs_path = os.path.join(exp_dir, 'exs.pl')

    # element
    bk_elements = []
    bk_elements.append(':-style_check(-discontiguous). % dont considere the discountinuity of clauses\n')
    exs_elements = []
    trace_id = 0

    try:
        with open(log_path, 'r') as f:
            for line in f:
                line = line.strip()

                # skip blank line
                if not line:
                    continue
                # handling end line
                if 'end' in line:
                    bk_elements.append('\n')
                    exs_elements.append(f'pos(failure({trace_id}))')
                    trace_id += 1
                    continue

                # Split the line into the event and the timestamp
                parts = line.rsplit(' ')
                time = parts[1][1:-1]
                time = int(float(time)*1000) # time in microseconds
                event = parts[2]
                element = parts[3][0:-1]

                # define and append bk_element
                firstChar = element[0]
                if (firstChar == 'T'):
                    task_id = element[-1]
                    bk_element = (f'{event}({trace_id}, {time}, {task_id}).')
                if (firstChar == 'C'):
                    task_id = element[-3]
                    chunk_id = element[-1]
                    bk_element = (f'{event}({trace_id}, {time}, {task_id}, {chunk_id}).')
                bk_elements.append(bk_element)

    # exception handling
    except FileNotFoundError:
        print(f"Error: Input file not found at {log_path}")
        return
    except Exception as e:
        print(f"An error occurred: {e}")
        return

    # Write the output files
    os.makedirs(os.path.dirname(bk_path), exist_ok=True)
    os.makedirs(os.path.dirname(exs_path), exist_ok=True)
    with open(bk_path, 'w') as output:
        for bk_element in bk_elements:
            output.write(f"{bk_element}\n")
    print('bk.pl sucessfully generated!!!')
    with open(exs_path, 'w') as output:
        for exs_element in exs_elements:
            output.write(f"{exs_element}\n")
    print('exs.pl sucessfully generated!!!')

### main ###
if __name__ == '__main__':
    args_pars = argparse.ArgumentParser()
    args_pars.add_argument('-pn', '--project_name',
                        type=str,
                        required=True,
                        help='name of experiment directory in my-experiments')
    args = args_pars.parse_args()
    log_to_bk(args.project_name)